### ISSUE TITLE
Missing Docker

### ISSUE THREAD

**Issue by diamondburned** [dylanaraps/promptless#11]
### Is your feature request related to a problem? Please describe.**

There is no Dockerfile for promptless. A lot of prompts have already moved to Docker: https://github.com/romkatv/powerlevel10k#try-it-in-docker

### Describe the solution you'd like**

A Dockerfile.

### Describe alternatives you've considered**

Death.

**Comment by dylanaraps** [comment]
Docker done boi

https://github.com/dylanaraps/promptless/pull/12
