### ISSUE TITLE
represent user home dir as `~`

### ISSUE THREAD

**Issue by vired** [dylanaraps/promptless#14]
**Is your feature request related to a problem? Please describe.**
i don't need to see `/home/vired` at the beginning of PWD. it cat be represent as `~`

**Describe the solution you'd like**
use `~` for user home dir instead for the full dir path

**Describe alternatives you've considered**
`\W`, but that is useless

**Additional context**
no

**Comment by vired** [comment]
`/home/vired/doc` to `~/doc`

**Comment by dylanaraps** [comment]
:-)

**Comment by mobop** [comment]
@dylanaraps , this would be nice , can you do this
