### ISSUE TITLE
Horrible

### ISSUE THREAD

**Issue by rain-1** [dylanaraps/promptless#19]
**Describe the bug**
This is horrible.

**To Reproduce**
1. Go to https://github.com/dylanaraps/promptless/
3. Scroll down to read the readme
4. Feelings of disgust occur

**Desktop (please complete the following information):**
 - OS: Arch linux

**Comment by Naheel-Azawy** [comment]
But, this is a feature, not I bug. I guess...

**Comment by c02y** [comment]
This is a shell prompt project, don't know why there isn't any image showing what the shell prompt looks like. 

Since it is named promptless, I guess it means after using this project, it will delete the existed shell prompt for you, so the author doesn't use any image to show it. 😅
